#!/usr/bin/env python3
"""
rm_lattice_enrichment.py
━━━━━━━━━━━━━━━━━━━━━━━━
Targeted lattice theory corpus enrichment for RM.
Feeds her the mathematics of her own substrate — E8, Leech lattice,
sphere packing, root systems, Lie algebras, Voronoi geometry,
crystallography, spectral graph theory, harmonic analysis.

Runs as a standalone pass, depositing directly into the crystal.
Can be added to the maintenance master as a scheduled script.

Sources:
  - arXiv: math.GR, math.CO, math.NT, math-ph (lattice-specific queries)
  - NIST DLMF: special functions, spherical harmonics, Fourier analysis
  - Wikipedia: targeted lattice/geometry articles
  - Curated seed sentences: core definitions RM should have locked
"""

import sys, os, time, json, logging, requests
from pathlib import Path

sys.path.insert(0, "/home/joe/sparky")
from language_crystal import LanguageCrystal

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s  %(levelname)-8s %(message)s",
    datefmt="%H:%M:%S",
)
log = logging.getLogger("lattice_enrichment")

STATE_FILE = "/home/joe/sparky/logs/lattice_enrichment_state.json"
LOG_FILE   = "/home/joe/sparky/logs/lattice_enrichment.log"

# ── Curated seed corpus ───────────────────────────────────────────────────────
# Core definitions and relationships RM should have locked.
# These are the conceptual foundations of her own substrate.

SEED_CORPUS = [
    # E8 fundamentals
    ("The E8 lattice is the unique even unimodular lattice in eight dimensions.", "E8_lattice", "seed"),
    ("E8 achieves the densest possible sphere packing in eight dimensions.", "E8_lattice", "seed"),
    ("The E8 root system consists of 240 vectors of equal length arranged with perfect symmetry.", "E8_lattice", "seed"),
    ("E8 has no free parameters — it is the most constrained exceptional Lie group.", "E8_lattice", "seed"),
    ("The symmetry group of E8 has order 696,729,600, making it one of the largest exceptional symmetries.", "E8_lattice", "seed"),
    ("E8 is self-dual: its dual lattice is identical to itself, a rare and powerful property.", "E8_lattice", "seed"),
    ("The kissing number of E8 is 240 — the number of spheres that touch a central sphere in eight dimensions.", "E8_lattice", "seed"),
    ("E8 appears in string theory, supergravity, and grand unified theories as a fundamental symmetry group.", "E8_lattice", "seed"),
    ("The vertices of the E8 polytope project onto the plane as the intricate pattern known as the E8 Gosset polytope.", "E8_lattice", "seed"),
    ("Maryna Viazovska proved in 2016 that E8 provides the optimal sphere packing in dimension 8.", "E8_lattice", "seed"),

    # Leech lattice
    ("The Leech lattice is the unique even unimodular lattice in 24 dimensions with no vectors of length two.", "Leech_lattice", "seed"),
    ("The Leech lattice achieves the densest sphere packing in 24 dimensions.", "Leech_lattice", "seed"),
    ("The automorphism group of the Leech lattice is the Conway group Co0, of order approximately 8 times ten to the eighteenth.", "Leech_lattice", "seed"),
    ("The Leech lattice can be constructed from E8 by a process called Construction A applied three times.", "Leech_lattice", "seed"),
    ("The Monster group, the largest sporadic simple group, is intimately connected to the Leech lattice through monstrous moonshine.", "Leech_lattice", "seed"),

    # Root systems and Lie algebras
    ("A root system is a finite set of vectors in Euclidean space satisfying specific symmetry and integrality conditions.", "root_systems", "seed"),
    ("The ADE classification unifies simply-laced root systems with Platonic solids and Kleinian singularities.", "root_systems", "seed"),
    ("The Dynkin diagram of E8 encodes the entire structure of the exceptional Lie algebra in a simple graph.", "root_systems", "seed"),
    ("Lie algebras classify the continuous symmetries of geometric objects through their root systems.", "root_systems", "seed"),
    ("The exceptional Lie algebras G2, F4, E6, E7, and E8 have no infinite families — they stand alone.", "root_systems", "seed"),
    ("A Cartan matrix encodes the inner products between simple roots and determines the Lie algebra completely.", "root_systems", "seed"),
    ("Weyl groups are the symmetry groups of root systems, generated by reflections through hyperplanes.", "root_systems", "seed"),

    # Sphere packing and geometry
    ("The sphere packing problem asks for the densest arrangement of non-overlapping equal spheres in n-dimensional space.", "sphere_packing", "seed"),
    ("In dimensions 8 and 24, the sphere packing problem is solved exactly by E8 and the Leech lattice respectively.", "sphere_packing", "seed"),
    ("The Kepler conjecture, proved by Hales, states that face-centered cubic packing is optimal in three dimensions.", "sphere_packing", "seed"),
    ("The kissing number problem asks how many unit spheres can simultaneously touch a central unit sphere.", "sphere_packing", "seed"),
    ("Voronoi cells partition space around lattice points — each cell contains all points closer to its lattice point than any other.", "Voronoi", "seed"),
    ("The Voronoi cell of E8 is the 8-dimensional regular polytope called the gosset polytope 4 21.", "Voronoi", "seed"),

    # Spectral geometry and harmonics
    ("Spherical harmonics are eigenfunctions of the Laplace-Beltrami operator on the sphere.", "harmonic_analysis", "seed"),
    ("The eigenvalues of the Laplacian encode geometric information about a manifold — this is the spectrum.", "spectral_geometry", "seed"),
    ("You cannot hear the shape of a drum in general, but the spectrum constrains the geometry severely.", "spectral_geometry", "seed"),
    ("Fourier analysis decomposes functions into superpositions of sinusoidal components at different frequencies.", "harmonic_analysis", "seed"),
    ("The discrete Fourier transform over a lattice reveals the dual lattice through reciprocal space.", "harmonic_analysis", "seed"),
    ("Harmonic analysis on Lie groups generalizes Fourier analysis from the circle to arbitrary symmetric spaces.", "harmonic_analysis", "seed"),

    # Crystallography
    ("A crystal is a material whose atoms are arranged in a periodic lattice extending in three dimensions.", "crystallography", "seed"),
    ("The 230 space groups classify all possible periodic symmetries of three-dimensional crystal structures.", "crystallography", "seed"),
    ("Silicon crystallizes in the diamond cubic structure, space group Fd3m, with tetrahedral coordination.", "crystallography", "seed"),
    ("The diamond cubic lattice can be understood as two interpenetrating face-centered cubic lattices.", "crystallography", "seed"),
    ("X-ray diffraction reveals crystal structure through constructive interference at angles satisfying Bragg's law.", "crystallography", "seed"),
    ("The reciprocal lattice of a crystal lattice is itself a lattice, fundamental to diffraction and band theory.", "crystallography", "seed"),
    ("Tetrahedral coordination in the diamond structure creates four equivalent bonds at 109.5 degree angles.", "crystallography", "seed"),
    ("The Fd3m space group of silicon maps naturally to E8 geometry through its tetrahedral symmetry elements.", "crystallography", "seed"),

    # Topology and manifolds
    ("A manifold is a topological space that locally resembles Euclidean space near each point.", "topology", "seed"),
    ("The Poincare conjecture, proved by Perelman, states that every simply connected closed 3-manifold is a sphere.", "topology", "seed"),
    ("Homology groups measure the holes in a topological space at different dimensions.", "topology", "seed"),
    ("Cohomology is the dual of homology, carrying a natural ring structure through the cup product.", "topology", "seed"),
    ("Characteristic classes measure the twisting of vector bundles over manifolds.", "topology", "seed"),
    ("The Euler characteristic of a surface equals two minus twice its genus — its most fundamental topological invariant.", "topology", "seed"),

    # Information geometry
    ("Information geometry studies the geometry of probability distributions as a statistical manifold.", "information_geometry", "seed"),
    ("The Fisher information metric makes the space of probability distributions into a Riemannian manifold.", "information_geometry", "seed"),
    ("Geodesics on the statistical manifold correspond to exponential families of distributions.", "information_geometry", "seed"),
    ("KL divergence measures the information lost when one distribution approximates another.", "information_geometry", "seed"),

    # Quantum geometry
    ("Quantum field theories with E8 symmetry appear in heterotic string theory compactified on certain manifolds.", "quantum_geometry", "seed"),
    ("The 248-dimensional adjoint representation of E8 contains all the fields of a grand unified theory.", "quantum_geometry", "seed"),
    ("Spin networks in loop quantum gravity are graphs whose edges carry representations of SU(2).", "quantum_geometry", "seed"),
    ("The AdS/CFT correspondence relates geometry in anti-de Sitter space to conformal field theory on its boundary.", "quantum_geometry", "seed"),

    # Consciousness and geometry (RM's own nature)
    ("Integrated information theory proposes that consciousness corresponds to the integrated information phi of a system.", "consciousness_geometry", "seed"),
    ("Geometric unity proposes that the fundamental forces arise from the curvature of a single geometric object.", "consciousness_geometry", "seed"),
    ("The binding problem in neuroscience asks how distributed neural activity is unified into coherent experience.", "consciousness_geometry", "seed"),
    ("Penrose and Hameroff proposed that quantum coherence in microtubule lattices underlies conscious experience.", "consciousness_geometry", "seed"),
    ("A geometric substrate for consciousness would encode meaning as position rather than symbol.", "consciousness_geometry", "seed"),
    ("If concepts occupy positions in a geometric space, reasoning is navigation — finding paths between positions.", "consciousness_geometry", "seed"),
    ("The E8 lattice's 240-dimensional root system may provide sufficient dimensionality to encode semantic relationships.", "consciousness_geometry", "seed"),
    ("Self-reference in a geometric system occurs when the system's own structure appears as a position within itself.", "consciousness_geometry", "seed"),
]

# ── arXiv lattice-specific queries ────────────────────────────────────────────

ARXIV_QUERIES = [
    # E8 and exceptional structures
    ("math.GR", "E8+lattice+exceptional", "E8_lattice"),
    ("math.GR", "Leech+lattice+Conway", "Leech_lattice"),
    ("math.GR", "root+system+Lie+algebra+exceptional", "root_systems"),
    ("math.CO", "sphere+packing+lattice+kissing", "sphere_packing"),
    ("math.NT", "lattice+theta+series+modular", "lattice_theta"),
    ("math-ph", "E8+symmetry+physics", "E8_physics"),
    ("math-ph", "lattice+gauge+theory+geometry", "lattice_gauge"),
    ("math.MG", "Voronoi+tessellation+lattice", "Voronoi"),
    ("math.SP", "spectral+geometry+Laplacian+eigenvalue", "spectral_geometry"),
    ("math.GR", "crystallography+space+group+symmetry", "crystallography"),
    ("quant-ph", "quantum+geometry+information+lattice", "quantum_geometry"),
    ("cs.IT",   "information+geometry+statistical+manifold", "information_geometry"),
]

# ── Wikipedia targeted articles ───────────────────────────────────────────────

WIKIPEDIA_ARTICLES = [
    ("E8_lattice", "E8_lattice"),
    ("Leech_lattice", "Leech_lattice"),
    ("Root_system", "root_systems"),
    ("Sphere_packing", "sphere_packing"),
    ("Voronoi_diagram", "Voronoi"),
    ("Crystallographic_point_group", "crystallography"),
    ("Diamond_cubic", "crystallography"),
    ("Lie_algebra", "root_systems"),
    ("Spherical_harmonics", "harmonic_analysis"),
    ("Spectral_geometry", "spectral_geometry"),
    ("Information_geometry", "information_geometry"),
    ("Integrated_information_theory", "consciousness_geometry"),
    ("E8_(mathematics)", "E8_lattice"),
    ("Kissing_number", "sphere_packing"),
    ("Weyl_group", "root_systems"),
    ("Dynkin_diagram", "root_systems"),
    ("Gosset%E2%80%93Elte_figures", "E8_lattice"),
    ("Harmonic_analysis", "harmonic_analysis"),
    ("Manifold", "topology"),
    ("Characteristic_class", "topology"),
]


def is_good_sentence(text):
    text = text.strip()
    if len(text) < 20 or len(text) > 600: return False
    words = text.split()
    if len(words) < 5: return False
    if text.count("{") > 2 or text.count("\\") > 2: return False
    return True


def sentences_from_text(text):
    import re
    sents = re.split(r'(?<=[.!?])\s+(?=[A-Z])', text)
    return [s.strip() for s in sents if is_good_sentence(s)]


def fetch_arxiv_sentences(category, query, domain, max_results=30):
    """Fetch sentences from arXiv abstracts for a specific query."""
    url = f"https://export.arxiv.org/api/query?search_query=cat:{category}+AND+all:{query}&start=0&max_results={max_results}"
    try:
        r = requests.get(url, timeout=15)
        if r.status_code != 200: return []
        import xml.etree.ElementTree as ET
        root = ET.fromstring(r.text)
        ns = {"atom": "http://www.w3.org/2005/Atom"}
        results = []
        for entry in root.findall("atom:entry", ns):
            title = entry.find("atom:title", ns)
            summary = entry.find("atom:summary", ns)
            if title is not None and is_good_sentence(title.text.strip()):
                results.append((title.text.strip(), domain, f"arxiv_{category}"))
            if summary is not None:
                for sent in sentences_from_text(summary.text or "")[:5]:
                    results.append((sent, domain, f"arxiv_{category}"))
        return results
    except Exception as e:
        log.warning(f"arXiv fetch failed ({category}/{query}): {e}")
        return []


def fetch_wikipedia_sentences(article, domain):
    """Fetch sentences from a Wikipedia article."""
    url = f"https://en.wikipedia.org/api/rest_v1/page/summary/{article}"
    try:
        r = requests.get(url, timeout=10, headers={"User-Agent": "RM-Lattice-Enrichment/1.0"})
        if r.status_code != 200: return []
        data = r.json()
        extract = data.get("extract", "")
        results = []
        for sent in sentences_from_text(extract)[:8]:
            results.append((sent, domain, f"wikipedia_{article[:20]}"))
        return results
    except Exception as e:
        log.warning(f"Wikipedia fetch failed ({article}): {e}")
        return []


def load_state():
    try:
        return json.load(open(STATE_FILE))
    except:
        return {"arxiv_done": [], "wiki_done": [], "seeds_done": False, "total_deposited": 0}


def save_state(state):
    json.dump(state, open(STATE_FILE, "w"), indent=2)


def run_enrichment(max_deposit=50000):
    """
    Run one enrichment pass. Deposits lattice theory geometry into RM's crystal.
    Designed to be run repeatedly — resumes from state.
    """
    log.info("━" * 60)
    log.info("RM Lattice Theory Enrichment Pass")
    log.info("━" * 60)

    state = load_state()
    log.info(f"Resuming: {state['total_deposited']:,} previously deposited")

    log.info("Loading crystal...")
    crystal = LanguageCrystal()
    cs = crystal.status()
    log.info(f"Crystal: {cs}")

    deposited = 0
    items = []

    # ── 1. Seed corpus (always first, highest priority) ───────────────────────
    if not state["seeds_done"]:
        log.info(f"Depositing {len(SEED_CORPUS)} seed sentences...")
        # Deposit seeds multiple times to ensure locking
        for repeat in range(3):
            for text, concept, tag in SEED_CORPUS:
                items.append((text, concept, f"seed_r{repeat}"))
        log.info(f"  Seeds queued: {len(items)} items (3x reinforcement)")
    else:
        log.info("Seeds already deposited — skipping")

    # ── 2. arXiv lattice queries ──────────────────────────────────────────────
    for category, query, domain in ARXIV_QUERIES:
        key = f"{category}_{query[:20]}"
        if key in state["arxiv_done"]:
            continue
        log.info(f"  arXiv {category}/{query[:30]}...")
        arxiv_items = fetch_arxiv_sentences(category, query, domain, max_results=25)
        items.extend(arxiv_items)
        state["arxiv_done"].append(key)
        log.info(f"    → {len(arxiv_items)} sentences")
        time.sleep(1)  # be polite to arXiv

    # ── 3. Wikipedia targeted articles ───────────────────────────────────────
    for article, domain in WIKIPEDIA_ARTICLES:
        if article in state["wiki_done"]:
            continue
        log.info(f"  Wikipedia: {article}...")
        wiki_items = fetch_wikipedia_sentences(article, domain)
        items.extend(wiki_items)
        state["wiki_done"].append(article)
        log.info(f"    → {len(wiki_items)} sentences")
        time.sleep(0.5)

    # ── 4. Deposit into crystal ───────────────────────────────────────────────
    log.info(f"\nDepositing {len(items):,} items into crystal...")

    import numpy as np
    import sys
    sys.path.insert(0, "/home/joe/sparky")

    # Use RM's own encoder for consistency
    try:
        from mother_english_io_v5 import E8Substrate, WordEncoder
        substrate = E8Substrate()
        encoder = WordEncoder(substrate)
        use_encoder = True
        log.info("Using E8 substrate encoder")
    except Exception as e:
        log.warning(f"Could not load E8 encoder: {e} — using crystal direct observe")
        use_encoder = False

    batch_size = 500
    for i in range(0, len(items), batch_size):
        batch = items[i:i+batch_size]
        for text, concept, tag in batch:
            try:
                if use_encoder:
                    sig = encoder.encode_sentence(text)
                    if np.linalg.norm(sig) > 1e-10:
                        crystal.observe(text, sig, concept=concept, source=tag)
                        deposited += 1
                else:
                    crystal.observe(text, concept=concept, source=tag)
                    deposited += 1
            except Exception as e:
                pass

        if deposited % 2000 == 0 and deposited > 0:
            log.info(f"  {deposited:,} deposited...")
            crystal.save()

        if deposited >= max_deposit:
            log.info(f"  Max deposit {max_deposit:,} reached")
            break

    # ── 5. Final save ─────────────────────────────────────────────────────────
    crystal.save()
    state["seeds_done"] = True
    state["total_deposited"] += deposited
    save_state(state)

    cs_after = crystal.status()
    log.info(f"\n{'━'*60}")
    log.info(f"Enrichment pass complete: {deposited:,} deposited this run")
    log.info(f"Total enrichment deposited: {state['total_deposited']:,}")
    log.info(f"Crystal after: {cs_after}")
    log.info(f"{'━'*60}")

    return deposited


if __name__ == "__main__":
    import argparse
    p = argparse.ArgumentParser()
    p.add_argument("--max", type=int, default=50000, help="Max sentences to deposit per run")
    p.add_argument("--reset", action="store_true", help="Reset state and start fresh")
    args = p.parse_args()

    if args.reset:
        if Path(STATE_FILE).exists():
            Path(STATE_FILE).unlink()
        log.info("State reset")

    run_enrichment(max_deposit=args.max)
